In [56]:
import pandas as pd
import seaborn as sns

In [57]:
data=pd.read_csv("insurance.csv")
data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [58]:
x=data.drop(columns=["charges"])
y=data["charges"]

In [15]:
x

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [59]:
x=pd.get_dummies(x,columns=["region"],drop_first= True,dtype=int)

In [60]:

x["sex"]= x["sex"].map({"female": 1, "male": 0})
x["smoker"]= x["smoker"].map({"yes": 1, "no": 0})
#x["age_smoker"]=x["age"]*x["smoker"]
#x["bmi_smoker"]=x["bmi"]*x["smoker"]

In [61]:
x

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,0,0,1
1,18,0,33.770,1,0,0,1,0
2,28,0,33.000,3,0,0,1,0
3,33,0,22.705,0,0,1,0,0
4,32,0,28.880,0,0,1,0,0
...,...,...,...,...,...,...,...,...
1333,50,0,30.970,3,0,1,0,0
1334,18,1,31.920,0,0,0,0,0
1335,18,1,36.850,0,0,0,1,0
1336,21,1,25.800,0,0,0,0,1
1337,61,1,29.070,0,1,1,0,0

In [62]:
from sklearn.linear_model import LassoCV
from sklearn.metrics import mean_squared_error,r2_score

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [64]:
a=[0.001,0.5,1,2,4,5,10]
model= LassoCV(
    alphas=a,
    cv=5,
    max_iter=1000
)
model.fit(X_train,y_train)
print("best alpha value:",model.alpha_)
y_pred=model.predict(X_test) 
m=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print(m,r2)

best alpha value: 10.0
33679511.300995946 0.7830609565864273